# ansible-galaxy install -r requirements.yml
# ansible-galaxy install geerlingguy.docker

---
- src: geerlingguy.docker
  version: 7.0.2
- src: https://github.com/geerlingguy/ansible-role-docker.git
  version: master
